export const LEAVE_RECORDS_DATA = [
  {
    empId: 50001,
    leaveType: "Annual",
    startDate: "1-Jan-2024",
    endDate: "3-Jan-2024",
    nod: 3,
    reason: "Personal time off",
    approver: "Namrata Singh",
    remark: "Accepted as per policy",
    status: "Approved",
  },
  {
    empId: 50001,
    leaveType: "Medical",
    startDate: "1-Jan-2024",
    endDate: "3-Jan-2024",
    nod: 1,
    reason: "Sick leave",
    approver: "Namrata Singh",
    remark: "Accepted as per policy",
    status: "Approved",
  },
  {
    empId: 50001,
    leaveType: "Unpaid",
    startDate: "1-Jan-2024",
    endDate: "3-Jan-2024",
    nod: 1,
    reason: "Urgent Work",
    approver: "Santosh Ranga",
    remark: "",
    status: "Denied",
  },
];
