// 1. Board of Directors or Owners
// 2. CEO (Chief Executive Officer) - 1
// 3. C-Suite Executives   -   1
// 4. Vice Presidents
// 5. Directors
// 6. Managers
// 7. Team Leaders
// 8. Specialists/Engineers
// 9. Analysts
// 10. Technicians     -   1
// 11. Associates/Entry-Level
// 12. Interns

export const PROFILE_DETAIL_DATA = [
  {
    empId: 50001,
    role: "ADMIN",
    email: "raj.singh@globant.com",
    firstName: "Raj",
    lastName: "Singh",
    gender: "Male",
    department: "CEO (Chief Executive Officer)",
    country: "India",
    state: "Madhya Pradesh",
    city: "Indore",
    dob: "9-Jan-1994",
    doj: "1-Jun-2021",
    photo: "hacker.png",
    address: "Cybercity Magarpatta",
    phoneNo: 8770349309,
    maritalStatus: "Married",
    raiting: "A+",
    skillSet:
      "Java-17,SpringBoot3,Spring-Native,ReactJs,Azure,Aritficail-Intelligence,Software Architect,Kubernetes,Jenkins,Agile,Kafka,NodeJs,Junit,Postman,Communicator",
  },
  {
    empId: 50002,
    role: "IT",
    email: "abhishek@globant.com",
    firstName: "Abhishek",
    lastName: "Kute",
    gender: "M",
    department: "Technicians",
    country: "India",
    state: "Uttar Pradesh",
    city: "Kanpur",
    dob: "1-Jan-1994",
    doj: "1-Jun-2021",
    photo: "man.png",
    address: "",
    phoneNo: 9999999999,
    maritalStatus: "Single",
    raiting: "B",
    skillSet:
      "Java-17,SpringBoot3,Spring-Native,ReactJs,Software Architect,Kubernetes,Jenkins,Agile,",
  },
  {
    empId: 50003,
    role: "IT",
    email: "namrata@globant.com",
    firstName: "Namrata",
    lastName: "Singh",
    gender: "F",
    department: "C-Suite Executive",
    country: "India",
    state: "Bihar",
    city: "Patna",
    dob: "9-Jan-1994",
    doj: "1-Jun-2021",
    photo: "panda.png",
    address: "",
    phoneNo: 9999999999,
    maritalStatus: "Single",
    raiting: "B",
    skillSet:
      "Java-17,SpringBoot3,Spring-Native,ReactJs,Azure,Aritficail-Intelligence,Software Architect,Kubernetes,Jenkins,Agile",
  },

  //  Vice presidents

  {
    empId: 50004,
    role: "IT",
    email: "anil@globant.com",
    firstName: "Anil",
    lastName: "Kale",
    gender: "M",
    department: "Vice President",
    country: "India",
    state: "Maharastra",
    city: "Pune",
    dob: "9-Jan-1994",
    doj: "1-Jun-2021",
    photo: "boy.png",
    address: "",
    phoneNo: 9999999999,
    maritalStatus: "Single",
    raiting: "B",
    skillSet:
      "Java-17,SpringBoot3,Spring-Native,ReactJs,Azure,Aritficail-Intelligence,Software Architect,Kubernetes,Jenkins,Agile",
  },
  {
    empId: 50005,
    role: "IT",
    email: "shubhangi@globant.com",
    firstName: "Shubhangi",
    lastName: "Pawar",
    gender: "F",
    department: "Vice President",
    country: "India",
    state: "Chattishgarh",
    city: "Raipur",
    dob: "9-Jan-1994",
    doj: "1-Jun-2021",
    photo: "panda.png",
    address: "",
    phoneNo: 9999999999,
    maritalStatus: "Single",
    raiting: "B",
    skillSet:
      "Java-17,SpringBoot3,Spring-Native,ReactJs,Azure,Aritficail-Intelligence,Software Architect,Kubernetes,Jenkins,Agile",
  },
  {
    empId: 50006,
    role: "IT",
    email: "vipul@globant.com",
    firstName: "Vipul",
    lastName: "Shrivastava",
    gender: "M",
    department: "Vice President",
    country: "India",
    state: "Telangana",
    city: "Hydrebad",
    dob: "9-Jan-1994",
    doj: "1-Jun-2021",
    photo: "panda.png",
    address: "",
    phoneNo: 9999999999,
    maritalStatus: "Single",
    raiting: "B",
    skillSet:
      "Java-17,SpringBoot3,Spring-Native,ReactJs,Azure,Aritficail-Intelligence,Software Architect,Kubernetes,Jenkins,Agile",
  },
  {
    empId: 50007,
    role: "IT",
    email: "santosh@globant.com",
    firstName: "Santosh",
    lastName: "Ranga",
    gender: "M",
    department: "Vice President",
    country: "India",
    state: "Telangana",
    city: "Hydrebad",
    dob: "9-Jan-1994",
    doj: "1-Jun-2021",
    photo: "panda.png",
    address: "",
    phoneNo: 9999999999,
    maritalStatus: "Single",
    raiting: "B",
    skillSet:
      "Java-17,SpringBoot3,Spring-Native,ReactJs,Azure,Aritficail-Intelligence,Software Architect,Kubernetes,Jenkins,Agile",
  },
  {
    empId: 50008,
    role: "IT",
    email: "darshil@globant.com",
    firstName: "Darshil",
    lastName: "Shah",
    gender: "M",
    department: "Vice President",
    country: "India",
    state: "Pune",
    city: "Maharastra",
    dob: "9-Jan-1994",
    doj: "1-Jun-2021",
    photo: "panda.png",
    address: "",
    phoneNo: 9999999999,
    maritalStatus: "Single",
    raiting: "B",
    skillSet:
      "Java-17,SpringBoot3,Spring-Native,ReactJs,Azure,Aritficail-Intelligence,Software Architect,Kubernetes,Jenkins,Agile",
  },
  {
    empId: 50009,
    role: "IT",
    email: "prasad@globant.com",
    firstName: "Prasad",
    lastName: "Kumar",
    gender: "M",
    department: "Director",
    country: "India",
    state: "Pune",
    city: "Maharastra",
    dob: "9-Jan-1994",
    doj: "1-Jun-2021",
    photo: "panda.png",
    address: "",
    phoneNo: 9999999999,
    maritalStatus: "Single",
    raiting: "B",
    skillSet:
      "Java-17,SpringBoot3,Spring-Native,ReactJs,Azure,Aritficail-Intelligence,Software Architect,Kubernetes,Jenkins,Agile",
  },
];
